# Generated by Django 4.2.1 on 2023-12-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('people', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentRoomRelation',
            fields=[
                ('payment_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('room_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospi.userdata')),
            ],
        ),
    ]
