# Generated by Django 4.2.1 on 2023-12-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospi', '0002_roomdata_alter_userdata_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentroomrelation',
            name='payment_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
