# Generated by Django 4.2.1 on 2023-12-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospi', '0003_alter_paymentroomrelation_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentroomrelation',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='paymentroomrelation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
