# Generated by Django 4.2.1 on 2023-12-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospi', '0004_remove_paymentroomrelation_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdata',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomdata',
            name='people_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
