# Generated by Django 4.2.1 on 2023-06-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compi_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('register', models.CharField(max_length=100)),
                ('explore', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='compi')),
            ],
        ),
    ]
