# Generated by Django 4.2.1 on 2023-06-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compi_cards',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
