# Generated by Django 4.2.1 on 2023-07-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compi_team',
            name='compi_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apis.compi'),
        ),
    ]
