# Generated by Django 3.2.12 on 2023-09-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_compi_reg_yearofstudy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='about',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='explore',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='max_team_length',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='register',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='stucture',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='timeline',
        ),
    ]
