# Generated by Django 4.2.2 on 2023-06-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_compi_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='compi_cards',
            name='genre',
            field=models.CharField(choices=[('1', 'first'), ('2', 'second'), ('3', 'third'), ('4', 'forth')], default=None, max_length=50),
        ),
    ]
