# Generated by Django 4.2.1 on 2023-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_compi_team_team_name_compi_team_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='compi_reg',
            name='tf_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compi',
            name='genre',
            field=models.CharField(choices=[('1', 'Zonals'), ('2', 'Compis'), ('3', 'Ideates'), ('4', 'forth')], default=None, max_length=50),
        ),
    ]
