# Generated by Django 4.2.2 on 2023-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_compi_team_team_name_compi_team_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNum', models.IntegerField()),
            ],
        ),
    ]
