# Generated by Django 3.2.12 on 2023-09-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_workshop_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
