# Generated by Django 4.2.1 on 2023-07-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_compi_reg_tf_id_alter_compi_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='compi',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compi',
            name='contact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compi',
            name='faqs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compi',
            name='rules',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compi',
            name='sponsorImg',
            field=models.ImageField(null=True, upload_to='compi_sponsors'),
        ),
        migrations.AddField(
            model_name='compi',
            name='stucture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compi',
            name='timeline',
            field=models.TextField(null=True),
        ),
    ]
