# Generated by Django 4.2.1 on 2023-08-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_compi_about_compi_contact_compi_faqs_compi_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('genre', models.CharField(choices=[('1', 'Zonals'), ('2', 'Compis'), ('3', 'Ideates'), ('4', 'forth')], default=None, max_length=50)),
                ('tag', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('max_team_length', models.IntegerField(blank=True, null=True)),
                ('prize', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('register', models.CharField(max_length=100)),
                ('explore', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='workshop')),
                ('sponsorImg', models.ImageField(blank=True, null=True, upload_to='workshop_sponsors')),
                ('about', models.TextField(null=True)),
                ('stucture', models.TextField(null=True)),
                ('timeline', models.TextField(null=True)),
                ('faqs', models.TextField(null=True)),
                ('rules', models.TextField(null=True)),
                ('contact', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='compi',
            name='sponsorImg',
            field=models.ImageField(blank=True, null=True, upload_to='compi_sponsors'),
        ),
        migrations.CreateModel(
            name='workshop_reg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tf_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('instiname', models.CharField(blank=True, max_length=255, null=True)),
                ('instiadress', models.TextField(blank=True, max_length=200, null=True)),
                ('instipincode', models.IntegerField(blank=True, null=True)),
                ('yearofstudy', models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('16', '6th Standard'), ('17', '7th Standard'), ('18', '8th Standard'), ('19', '9th Standard'), ('20', '10th Standard'), ('21', '11th Standard'), ('22', '12th Standard')], max_length=255, null=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.workshop')),
            ],
        ),
    ]
