# Generated by Django 3.2.12 on 2023-09-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_workshop_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='statement',
            field=models.FileField(blank=True, null=True, upload_to='ProblemStatements'),
        ),
    ]
