# Generated by Django 3.2.12 on 2023-09-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_workshop_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop_reg',
            old_name='tf_id',
            new_name='worksho_id',
        ),
        migrations.RemoveField(
            model_name='workshop_reg',
            name='address',
        ),
        migrations.RemoveField(
            model_name='workshop_reg',
            name='country',
        ),
        migrations.RemoveField(
            model_name='workshop_reg',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='workshop_reg',
            name='instiadress',
        ),
        migrations.RemoveField(
            model_name='workshop_reg',
            name='instiname',
        ),
        migrations.RemoveField(
            model_name='workshop_reg',
            name='instipincode',
        ),
        migrations.RemoveField(
            model_name='workshop_reg',
            name='yearofstudy',
        ),
    ]
