# Generated by Django 4.2.2 on 2023-08-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_notifying'),
        ('apis', '0006_workshop_alter_compi_sponsorimg_workshop_reg'),
    ]

    operations = [
    ]
