# Generated by Django 4.2.1 on 2023-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_workshop_alter_compi_sponsorimg_workshop_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='compi',
            name='statement',
            field=models.FileField(blank=True, null=True, upload_to='compi_statements'),
        ),
    ]
