# Generated by Django 4.2.1 on 2023-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_compi_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compi',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compi',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compi',
            name='faqs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compi',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compi',
            name='stucture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compi',
            name='timeline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
