# Generated by Django 3.2.12 on 2023-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20230927_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_reg',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
