# Generated by Django 3.2.12 on 2023-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_workshop_reg_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='paymentLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
