# Generated by Django 4.2.1 on 2023-08-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_notifying'),
        ('apis', '0008_alter_compi_about_alter_compi_contact_and_more'),
    ]

    operations = [
    ]
