# Generated by Django 3.2.12 on 2023-10-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_workshop_paymentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_reg',
            name='ca_referral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
