# Generated by Django 4.2.1 on 2023-08-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_merge_20230809_1952'),
        ('apis', '0009_merge_20230809_1404'),
    ]

    operations = [
    ]
