# Generated by Django 4.2.1 on 2023-10-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_workshop_reg_ca_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sponsorLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
