# Generated by Django 4.2.1 on 2023-08-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_merge_20230812_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compi_reg',
            name='ca_refral',
        ),
        migrations.AddField(
            model_name='compi_reg',
            name='zonals',
            field=models.CharField(blank=True, choices=[('1', 'Mumbai'), ('2', 'Bhopal'), ('3', 'Lucknow'), ('4', 'Jaipur'), ('5', 'Bangalore')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compi',
            name='statement',
            field=models.FileField(blank=True, null=True, upload_to='ProblemStatements'),
        ),
    ]
