# Generated by Django 4.2.2 on 2023-08-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_remove_compi_reg_ca_refral_compi_reg_zonals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compi',
            name='about',
        ),
        migrations.RemoveField(
            model_name='compi',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='compi',
            name='explore',
        ),
        migrations.RemoveField(
            model_name='compi',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='compi',
            name='register',
        ),
        migrations.RemoveField(
            model_name='compi',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='compi',
            name='stucture',
        ),
        migrations.RemoveField(
            model_name='compi',
            name='timeline',
        ),
    ]
