# Generated by Django 4.2.1 on 2023-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_remove_compi_reg_ca_refral_compi_reg_zonals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compi_team',
            name='single_parti',
            field=models.BooleanField(default=False),
        ),
    ]
