# Generated by Django 4.2.1 on 2023-08-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_compi_team_single_parti'),
        ('apis', '0012_remove_compi_about_remove_compi_contact_and_more'),
    ]

    operations = [
    ]
