# Generated by Django 4.2.2 on 2023-08-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_remove_compi_about_remove_compi_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compi',
            name='reg_count',
            field=models.IntegerField(default=0),
        ),
    ]
