# Generated by Django 3.2.12 on 2023-10-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_workshop_ex_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
