# Generated by Django 4.2.1 on 2023-09-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_compi_reg_count'),
        ('apis', '0013_merge_20230827_1657'),
    ]

    operations = [
    ]
