<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-09-02 07:02
=======
<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-09-01 22:43
=======
# Generated by Django 4.2.1 on 2023-09-02 22:24
>>>>>>> 1f43a19b657b0c8d5fa0daeb90d9dec391b3d28f
>>>>>>> a6f45edb4782aa4a62d0e1a1a25b2d84dcd7f3d2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_compi_reg_count'),
        ('apis', '0013_merge_20230827_1657'),
    ]

    operations = [
    ]
