# Generated by Django 3.2.12 on 2023-10-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_workshop_workshop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robowars',
            fields=[
                ('robowar_id', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='robowars')),
                ('statement', models.FileField(blank=True, null=True, upload_to='ProblemStatements')),
            ],
        ),
        migrations.CreateModel(
            name='robowar_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robowar_id', models.CharField(blank=True, max_length=50, null=True)),
                ('team_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_leader_name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_leader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('team_leader_phone', models.CharField(blank=True, max_length=254, null=True)),
                ('member1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('member1_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member1_phone', models.CharField(blank=True, max_length=254, null=True)),
                ('member2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('member2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member2_phone', models.CharField(blank=True, max_length=254, null=True)),
                ('member3_name', models.CharField(blank=True, max_length=50, null=True)),
                ('member3_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member3_phone', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.robowars')),
            ],
        ),
    ]
