# Generated by Django 4.2.1 on 2023-09-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_merge_0013_compi_reg_count_0013_merge_20230827_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='compi',
            name='sponsorLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notifying',
            name='loc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
