# Generated by Django 3.2.12 on 2023-10-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_robowar_reg_robowars'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobowarTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member1_email',
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member1_name',
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member1_phone',
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member2_email',
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member2_name',
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member2_phone',
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member3_email',
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member3_name',
        ),
        migrations.RemoveField(
            model_name='robowar_reg',
            name='member3_phone',
        ),
        migrations.AddField(
            model_name='robowar_reg',
            name='members',
            field=models.ManyToManyField(to='apis.RobowarTeamMember'),
        ),
    ]
