# Generated by Django 3.2.12 on 2023-10-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_auto_20231010_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='robowar_reg',
            name='team_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
