# Generated by Django 3.2.12 on 2023-10-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_robowar_reg_team_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='compi',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
