# Generated by Django 3.2.12 on 2023-10-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_auto_20231013_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccoReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acco_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=255, null=True)),
                ('aadhar_proof', models.FileField(blank=True, null=True, upload_to='acco')),
                ('no_of_male', models.IntegerField(blank=True, null=True)),
                ('no_of_female', models.IntegerField(blank=True, null=True)),
                ('checkin', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
