# Generated by Django 3.2.12 on 2023-10-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_accoreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='accoreg',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accoreg',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accoreg',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='acco'),
        ),
    ]
