# Generated by Django 3.2.12 on 2023-10-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_auto_20231028_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compi_reg',
            name='zonals',
            field=models.CharField(blank=True, choices=[('1', 'Mumbai'), ('2', 'Bhopal'), ('3', 'Lucknow'), ('4', 'Jaipur'), ('5', 'Bangalore'), ('6', 'Nepal')], max_length=255, null=True),
        ),
    ]
