# Generated by Django 3.2.12 on 2023-11-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_sustainregtest_sustainregwebinar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ching_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('summit', models.CharField(blank=True, choices=[('Industry', 'Industry'), ('Fintech', 'Fintech')], max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='summit_speakers')),
            ],
        ),
    ]
