# Generated by Django 4.2.1 on 2023-11-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_summitreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regLink', models.CharField(blank=True, max_length=255, null=True)),
                ('exploreLink', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='summit')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
