# Generated by Django 4.2.1 on 2023-11-30 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0026_summits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summitreg',
            name='summit',
        ),
        migrations.AddField(
            model_name='summitreg',
            name='summitisho',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apis.summits'),
        ),
    ]
