# Generated by Django 4.2.1 on 2023-12-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0027_remove_summitreg_summit_summitreg_summitisho'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFT',
            fields=[
                ('ift_id', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='ift')),
                ('statement', models.FileField(blank=True, null=True, upload_to='ift/ps')),
            ],
        ),
        migrations.AlterField(
            model_name='compi',
            name='genre',
            field=models.CharField(choices=[('1', 'Zonals'), ('2', 'Compis'), ('3', 'Ideates'), ('4', 'forth'), ('5', 'dummy')], default=None, max_length=50),
        ),
    ]
