# Generated by Django 4.2.1 on 2023-12-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0030_faces'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='ching_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
