# Generated by Django 3.2.12 on 2023-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_id', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(default=None, max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('recipient_list', models.FileField(blank=True, null=True, upload_to='mail_recipients')),
            ],
        ),
    ]
