# Generated by Django 3.2.12 on 2023-10-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='your_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
