"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a@f*cs+m#hx@2nfd5gqvxiw7wh)-#o!l8sequadt^8^@=26rr6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
=======
PASSWORD = 'yatharth.techfest'

>>>>>>> ebf728e49cddf0728aaae025045fa1c0c76103a2
ALLOWED_HOSTS = ['44.212.59.103', 'techfest.org', 'rain.techfest.org', '127.0.0.1', 'localhost']


#Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apis',
    'admins',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# CSRF_TRUSTED_ORIGINS = ['http://localhost:3000']
# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOWED_ORIGINS = ['http://localhost:3000']

CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000', 'https://techfest.org', 'https://rain.techfest.org', 
]

CSRF_TRUSTED_ORIGINS = ['https://rain.techfest.org', 'https://techfest.org', 'http://localhost:3000']

# CORS_ALLOW_HEADERS = [
#     'x-google-uid', 
#     'content-type',
# ]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

<<<<<<< HEAD
=======
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'tfdb',
#         'USER': 'yatharth',
#         'PASSWORD': PASSWORD,
#         'HOST': 'tfdb.cufxluinuzsz.us-east-1.rds.amazonaws.com',
#         'PORT': '3306',
#     }
# }

>>>>>>> ebf728e49cddf0728aaae025045fa1c0c76103a2
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tfdb',
        'USER': 'yatharth',
        'PASSWORD': 'yathath.techfest',
        'HOST': 'tfdb.cufxluinuzsz.us-east-1.rds.amazonaws.com',
        'PORT': '3306',
    }
}

<<<<<<< HEAD
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
=======


>>>>>>> ebf728e49cddf0728aaae025045fa1c0c76103a2

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

<<<<<<< HEAD
STATIC_URL = 'apo/'
STATIC_ROOT = os.path.join(BASE_DIR, 'apo/')
=======
STATIC_URL = 'apos/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
>>>>>>> ebf728e49cddf0728aaae025045fa1c0c76103a2


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Taaki SES Pareshan na karien

# EMAIL_USE_TLS = True
# EMAIL_HOST = 'email-smtp.ap-south-1.amazonaws.com'
# EMAIL_HOST_USER = 'AKIATEUUM33B5ZYQDREC'
# EMAIL_HOST_PASSWORD = 'BGfZ4WxwU9AOfkVQL7hib9Vwlb5eYFtYE/hcQjYqcLDO'
# EMAIL_PORT = 587


# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST_USER = 'cuzallis11@gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_PASSWORD = ''

EMAIL_BACKEND = 'django_ses.SESBackend'
# AWS_SES_REGION_NAME = 'us-east-1'
# AWS_SES_REGION_ENDPOINT = 'email-smtp.us-east-1.amazonaws.com'
AWS_ACCESS_KEY_ID = 'AKIATEUUM33B2WR5KA5P'
AWS_SECRET_ACCESS_KEY = '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' 
# EMAIL_HOST_USER = 'noreply@techfest.org'

