# Generated by Django 4.2.2 on 2023-12-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(max_length=100)),
                ('team2_name', models.CharField(max_length=100)),
                ('team1_image', models.ImageField(upload_to='team_images/')),
                ('team2_image', models.ImageField(upload_to='team_images/')),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3')])),
                ('match_time', models.TimeField()),
                ('points_awarded', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_team', models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robowarsbet.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robowarsbet.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(through='robowarsbet.UserMatch', to='robowarsbet.match'),
        ),
    ]
