# Generated by Django 4.2.2 on 2023-12-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robowarsbet', '0002_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
