# Generated by Django 4.2.2 on 2023-12-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robowarsbet', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(blank=True, choices=[(1, 'Team 1'), (2, 'Team 2'), (3, 'Team 3')], null=True),
        ),
    ]
