# Generated by Django 4.2.2 on 2023-12-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robowarsbet', '0004_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team3_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AddField(
            model_name='match',
            name='team3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usermatch',
            name='selected_team',
            field=models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2'), (3, 'Team 3')]),
        ),
    ]
