# Generated by Django 4.2.2 on 2023-12-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robowarsbet', '0005_match_team3_image_match_team3_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Finished'), (2, 'Ongoing'), (3, 'Betting-On'), (4, 'Show')], null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team4_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AddField(
            model_name='match',
            name='team4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team5_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AddField(
            model_name='match',
            name='team5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team6_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
        migrations.AddField(
            model_name='match',
            name='team6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Robowars'), (2, 'IFT'), (3, 'Competitions')], null=True),
        ),
    ]
