# Generated by Django 4.2.2 on 2023-12-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robowarsbet', '0006_match_status_match_team4_image_match_team4_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_points',
        ),
        migrations.AddField(
            model_name='user',
            name='total_points_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, choices=[('Finished', 'Finished'), ('Ongoing', 'Ongoing'), ('Betting-On', 'Betting-On'), ('Future', 'Future')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Robowars'), (2, 'IFT'), (3, 'Drone-Racing')], null=True),
        ),
    ]
