# Generated by Django 4.2.2 on 2023-12-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robowarsbet', '0007_remove_user_total_points_user_total_points_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.IntegerField(blank=True, choices=[('Finished', 'Finished'), ('Ongoing', 'Ongoing'), ('Betting-On', 'Betting-On'), ('Future', 'Future')], null=True),
        ),
    ]
