# Generated by Django 4.2.2 on 2023-12-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robowarsbet', '0008_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(blank=True, choices=[('Finished', 'Finished'), ('Ongoing', 'Ongoing'), ('Betting-On', 'Betting-On'), ('Future', 'Future')], max_length=100, null=True),
        ),
    ]
