# Generated by Django 4.0.6 on 2022-11-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateimage',
            name='comp_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateimage',
            name='comp_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateimage',
            name='comp_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateimage',
            name='name_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateimage',
            name='name_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateimage',
            name='name_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateimage',
            name='rank_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateimage',
            name='rank_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateimage',
            name='rank_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
