# Generated by Django 4.0.6 on 2022-11-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_certificateimage_qr_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateimage',
            name='qr_scale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
