# Generated by Django 4.0.6 on 2022-11-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificateimage_qr_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('ca_id', models.CharField(blank=True, max_length=255)),
                ('image_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LetterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=20, unique=True)),
                ('template', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
