# Generated by Django 4.0.6 on 2022-12-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
